name: woodwater media
favicon: null
layout_spectrum: 0.21879
typography_spectrum: 0.15403
title: 'go on, tell your story. . .'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffee9'
    - '#c8ccd7'
    - '#110706'
    - '#886a50'
    - '#4c392a'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
