name: woodwater media
favicon: null
layout_spectrum: 0.11288
typography_spectrum: 0.16525
title: 'go on, tell your story. . .'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#095354'
    - '#d6d6d6'
    - '#010109'
    - '#979797'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
