name: woodwater media
favicon: null
layout_spectrum: 0.23165
typography_spectrum: 0.16525
title: 'woodwater media go on, tell your story. . .'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#095354'
    - '#d6d6d6'
    - '#010109'
    - '#979797'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.7915508986916393
purpose: []
