name: woodwater media
favicon: null
layout_spectrum: 0.21879
typography_spectrum: 0.15403
title: 'go on, tell your story. . .'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#180f08'
    - '#382b1a'
    - '#7c7d75'
    - '#ddc89d'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
