name: woodwater media
favicon: null
layout_spectrum: 0.5433264966122806
typography_spectrum: 0.11140588880516589
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8444431794341654
  lightness: 0.42188192158937454
  saturation: 0.15733140474185348
  rhythmicContrast: 0.7915508986916393
purpose: []
