name: woodwater media
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11140588880516589
title: 'go on, tell your story. . .'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#095354'
    - '#d6d6d6'
    - '#010109'
    - '#979797'
  brandStrength: 0.8444431794341654
  lightness: 0.42188192158937454
  saturation: 0.5
  rhythmicContrast: 0.7915508986916393
purpose: []
